version: '3.9'
services:
  news-api:
    container_name: news-api
    build:
      dockerfile: ./packages/api-gateway/Dockerfile
      context: .
    ports:
      - 5002:3002
    environment:
      PORT: 3002
      MONGO_HOST: news-mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    depends_on:
      - news-mongo
    networks:
      - news-network
  news-webapp:
    container_name: news-webapp
    build:
      dockerfile: ./packages/webapp/Dockerfile
      context: .
    ports:
      - 5000:3000
    networks:
      - news-network
  news-nginx:
    container_name: news-nginx
    build: nginx
    ports:
      - 9000:9000
    depends_on:
      - news-webapp
      - news-api
    networks:
      - news-network
  news-mongo:
    image: mvertes/alpine-mongo
    container_name: news-mongo
    ports:
      - 27017:27017
    volumes:
      - ${DATA_PATH}/mongo-data:/data/db
    networks:
      - news-network
networks:
  news-network:
    name: news-network
