version: '3.9'
services:
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ${DATA_PATH}/mongo-data:/data/db
    networks:
      - news-network
networks:
  news-network:
    name: news-network
